### ISSUE TITLE
Dependency confusion supply-chain vulnerability detected

### ISSUE THREAD

**Issue by ashishbijlani** [chaturanga50/iam-ssh-cli#1]
I'm a Cybersecurity researcher developing PackjGuard [1]. Our tool has detected a dependency confusion vulnerability in this repository.

The package `iam-ssh-cli` mentioned in the README at [line 20](https://github.com/chaturanga50/iam-ssh-cli/blob/main/README.rst?plain=1#L20) does not exist on public PyPI registry. A bad actor can hijack this package to propagate malicious code.

Not only your apps/service is vulnerable to this attack, but the users of your open-source Github repo are also vulnerable to this attack. Please register a placeholder package for `iam-ssh-cli` on public PyPI soon to remediate.

Thanks!

PackjGuard is a Github app that monitors repos for malicious/vulnerable dependencies and mitigates attacks by creating pull requests for automatic remediation https://github.com/marketplace/packjguard

**Comment by chaturanga50** [comment]
@ashishbijlani fixed the GitHub action pipeline responsible to publish the package, now releases are available at the PyPI repo - https://pypi.org/project/iam-ssh-cli/#history
